config/routes.rb
StreetFeast::Application.routes.draw do
  get "blog/create"
  get "management/show_users"
  get "home/index"
  get "home/dashboard"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  get 'test_email' => 'application#test_email'

  get 'home/blacklist' => 'home#blacklist'

  post 'home/blacklist' => 'home#blacklist'

  get 'home/analytics' => 'home#analytics'

  post 'home/analytics' => 'home#analytics'

  get 'home/undo_blacklist' => 'home#undo_blacklist'

  post 'home/undo_blacklist' => 'home#undo_blacklist'
  
  get '/users' => 'user#index'

  get 'home/dashboard' => 'home#dashboard', as: :dashboard

  get 'home/dashboard_user' => 'home#dashboard_user'

  get 'user/:id/edit' => 'user#edit'

  get 'home/new_sms' => 'home#new_sms'

  post 'home/send_sms' => 'home#send_sms'

  patch 'user/:id/update' => 'user#update'

  post 'blog/create' => 'blog#create'

  post 'blog/create_blog_user' => 'blog#create_blog_user'

  get 'blog/new' => 'blog#new'

  get '/blogs' => 'blog#index'

  get 'blog/:id/edit' => 'blog#edit'

  get 'blog/:id' => 'blog#show'

  patch 'blog/update/:id' => 'blog#update'

  post 'blog/add_picture_to_blog' => 'blog#add_picture_to_blog'

  get 'user/show/:id' => 'user#show'

  patch 'user/update/:id' => 'user#update'

  delete 'user/photo_remove/:id' => "user#photo_remove"

  patch 'blog/update_blog_user/:id' => 'blog#update_blog_user'
  
  get 'restaurant/new/:id' => 'restaurant#new'

  post 'restaurant/create' => 'restaurant#create'

  get 'restaurant/:id' => 'restaurant#show'

  get 'restaurant/show_for_user/:id' => 'restaurant#show_for_user'

  get 'restaurant/pic/show/:id' => 'restaurant#show_pic'

  get 'like/pic_like/:id' => 'like#pic_like'

  get 'restaurant/address/:id' => 'restaurant#address'

  patch 'restaurant/update/:id' => 'restaurant#update'
  
  get 'menu/:id' => "menu#show"

  get "/restaurants" => "restaurant#index"
  get 'support_ticket/new' => "supportticket#new"

  post 'support_ticket/create' => 'supportticket#create'

  get '/support_tickets' => 'supportticket#index'

  get '/support_ticket/show/:id' => 'supportticket#show'

  get 'support_ticket/resolve' => "supportticket#resolve"

  get 'subscription/new' => 'subscription#new'

  post 'menu/create/:id' => 'menu#create'

  get '/menu/is_available/:id' => 'menu#is_available'

  get '/subscriptions' => 'subscription#index'

  get '/subscriptions/send_newsletter' => 'subscription#send_newsletter'

  post '/menu/edit_price' => 'menu#edit_price'

  get '/feedback/create' => 'feedback#create'

  get "payment/new" => "payment#new"

  post '/payment/create' => 'payment#create'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :blogs
	has_many :addresses
	has_many :pictures
	accepts_nested_attributes_for :addresses
	has_many :menus
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController

  def new 
    @blog_id=params[:id]
    @restaurant = Restaurant.new
    @address = @restaurant.addresses.build
    @menu = Menu.new
    render partial: "new"
  end

  def create
    @restaurant = Restaurant.where("associated_blogs LIKE ?","%#{params[:blog_id]}%")
    if @restaurant.nil?
      params[:restaurant][:is_blacklisted] = false
      @restaurant = Restaurant.create(restaurant_params)
      @restaurant.update_attribute(:associated_blogs,params[:blog_id])
      menu_item_name = params[:menu_item_name]
      menu_item_price = params[:menu_item_price]
      restaurant_id = @restaurant.id
      if params[:menu_item_name].present? && params[:menu_item_price].present?
        menu_item_name.keys.each_with_index do |key, index|
          item_name = menu_item_name.values[index]
          item_price = menu_item_price.values[index]
          if item_name.present? && item_price.present?
            Menu.create(:item_name=>item_name,:price=>item_price,:restaurant_id=>restaurant_id)
          end
        end
      end
      if params[:restaurant][:address][:address_line].present? && params[:restaurant][:address][:latitude].present? && params[:restaurant][:address][:longitude].present?
        @address = Address.create(:address_line => params[:restaurant][:address][:address_line],:latitude =>params[:restaurant][:address][:latitude],:longitude=>params[:restaurant][:address][:longitude],:restaurant_id=>@restaurant.id)
      end
      flash[:notice] = "Restaurant has been created successfully!"
      redirect_to :back
    else
      flash[:notice] = "Restaurant already exists for this blog!"
      redirect_to :back
    end
  end

  def show
    @restaurant = Restaurant.find_by_id(params[:id])
    @pictures_res = @restaurant.pictures
    @menu_for_restaurant = Menu.where("restaurant_id=?",@restaurant.id)
    
  end


  def show_for_user
    @restaurant = Restaurant.find_by_id(params[:id])
    @pictures_res = @restaurant.pictures
  end

  def show_pic
    @picture = Picture.find_by_id(params[:id])
    if current_user.present?
      @like = Like.where("picture_id=?  and user_id =? and is_liked =?",@picture.id,current_user.id,true).first
    end
    if @like.present?
      render json: {pic: @picture.avatar, id: @picture.id, is_liked: true}
    else
      render json: {pic: @picture.avatar, id: @picture.id, is_liked: false}
    end
  end

  def address
    @address = Address.where("restaurant_id =?",params[:id]).first
    render json: {lat: @address.latitude,long: @address.longitude}
  end
  
  def update
    blog_ids=[]
    @restaurant = Restaurant.find_by_id(params[:id])
    if @restaurant.present?
      @restaurant_address = Address.where("restaurant_id=?",@restaurant.id).first
      if params[:restaurant][:address].present?
        restaurant_latitude = params[:restaurant][:address][:latitude]
        restaurant_longitude = params[:restaurant][:address][:longitude]
        restaurant_address_line = params[:restaurant][:address][:address_line]
        @restaurant_address.update_attribute(:latitude,restaurant_latitude)  
        @restaurant_address.update_attribute(:longitude,restaurant_longitude)  
        @restaurant_address.update_attribute(:address_line,restaurant_address_line)
        @restaurant_address.save
      end
      params[:restaurant][:associated_blogs].split(",").each do |check_blog_id|
        blog = Blog.where("id=?",check_blog_id).first
        if blog.present?
          blog_ids << blog.id
        end
      end
      params[:restaurant][:associated_blogs] = blog_ids.uniq.join(",")
      @restaurant.update_attributes(restaurant_params)
    end
    flash[:notice] = "Restaurant details has been updated successfully!"
    redirect_to :back      
  end
  def index
    respond_to do |format|
      format.html
      format.json { render json: RestaurantDatatable.new(view_context) }
    end
  end


 private
  def restaurant_params
    params.require(:restaurant).permit(:name,:cuisine,:cost_for_two,:contact_number, :description,:opening_time,:closing_time,:operator,:closed_on,:is_blacklisted,:is_deactive,:associated_blogs)
  end
end

app/views/restaurant/_new.html.erb
<script type="text/javascript" src="http://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js"></script>
<style type="text/css">
  .ui-autocomplete{z-index: 9999999}
</style>
<%= form_for (@restaurant),url: "/restaurant/create" do |f| %>
  <%= hidden_field_tag :blog_id, @blog_id %>
  <div class="field">
    <%= f.text_field :name,:class=>"form-control",:placeholder => "Name", autofocus: true ,:required=>true%>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :description,:placeholder => "Description",:class=>"form-control",:required=>true %>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="field">
        <%= f.text_field :closed_on,:class=>"form-control",:placeholder => "Closed On",:id=>"closed_on" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="field">
        <%= f.text_field :cost_for_two,:class=>"form-control" ,:placeholder => "Cost for two",:required=>true%>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="field">
        <%= f.text_field :opening_time,:id =>"timepickeropen",:class=>"form-control" ,:placeholder => "Opening Time"%>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="field">
        <%= f.text_field :closing_time,:id =>"timepickerclose",:class=>"form-control" ,:placeholder => "Closing Time"%>
      </div>
    </div>
  </div>
  <br>
  <div class="field">
    <%= f.text_field :cuisine,:class=>"form-control",:placeholder => "Cuisine",:id=>"cuisine"%>
  </div>
  <br>
  <div class="field">
    <%= f.text_field :operator,:class=>"form-control",:placeholder => "Operator",:required=>true %>
  </div>
  <br>
  <%= f.fields_for @address do |a|  %>
    <div class="field">
      <%= a.text_area :address_line,:class=>"form-control",:placeholder => "Address",:required=>true%>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="field">
          <%= a.text_field :latitude,:class=>"form-control",:placeholder => "Latitude",:id=>"latitude"%>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="field">
          <%= a.text_field :longitude,:class=>"form-control",:placeholder => "Longitude" ,:id =>"longitude" %>
        </div>
      </div>
    </div>
  <% end %>
  <hr>

  <strong>Menu</strong>
  <br>
  <div class="menu_list">
    <%= f.fields_for @menu do |menu|  %>
      <div class="row">
        <div class="col-sm-6">
            <div class="field">
              <%= menu.text_field :item_name,:class=>"form-control",:placeholder => "Item name",:id=>"item_name"%>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="field">
              <%= menu.text_field :price,:class=>"form-control",:placeholder => "Price" ,:id =>"price" %>
            </div>
          </div>
      </div>
      <br>
    <% end %>
  </div>

  <div class="field">
    <%= button_tag "Add more",:id => "add_more",:class=>"btn btn-danger" %>
  </div>
  <hr>
 
  <br>
  <div class="row">
    <div class="col-sm-10">
      <div class="field">
        <a><input id="search-input" class="form-control" type="text" placeholder="Search Location"></a>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="field">
        <img src="/assets/search.png" style="height: 25px;width: 25px;" id="search">
      </div>
    </div>
  </div>
  <br>
    <div id="map_canvas" style="width: auto; height: 250px;" class="map_location"></div>
  <br>
  <div class="actions">
    <button type="submit" class="btn btn-primary btn_large" style="width: 150px;" >Add</button>
  </div>
<% end %>
<script type="text/javascript">
  $( document ).ready(function() {
    $(".map_location").hide(); 
    $("#item_name").last().attr("name","menu_item_name[item_name1]");
    $("#price").last().attr("name","menu_item_price[price1]");
  });

  $('#timepickeropen').timepicker();
  $('#timepickerclose').timepicker();

  
  $('#closed_on').tokenfield({
    autocomplete: {
      source: ['Sunday','Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday'],
      delay: 100
    },
    showAutocompleteOnFocus: true
  })
  $('#cuisine').tokenfield({
    autocomplete: {
      source: ['Chinese','Moghlai','Desert','Indian','South Indian'],
      delay: 100
    },
    showAutocompleteOnFocus: true
  })


  $("#search").on("click",function(){
    var geocoder = new google.maps.Geocoder();
    $(".map_location").show();  
    var add = $("#search-input").val();
    geocoder.geocode( { 'address': add}, function(results, status) {

      if (status == google.maps.GeocoderStatus.OK) 
      {
        var latitude = results[0].geometry.location.lat();
        var longitude = results[0].geometry.location.lng();  
        // alert(latitude);
        // alert(longitude);
        var map;
        function initialize() 
        {
          var myLatlng = new google.maps.LatLng(latitude, longitude);

          var myOptions = {
              zoom: 15,
              center: myLatlng,
              mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

          var marker = new google.maps.Marker({
              draggable: true,
              position: myLatlng,
              map: map
          });

          google.maps.event.addListener(marker, 'dragend', function (event) 
          {
            document.getElementById("latitude").value = event.latLng.lat();
            document.getElementById("longitude").value = event.latLng.lng();
          });
        }
        google.maps.event.addDomListener(window, "load", initialize());
      }
    }); 
  });




  $("#add_menu").on("click",function(e){
    e.preventDefault();
    $(".menu_list").show();
    $("#menu").hide();
    $("#add_more").show();
  });

  $("#add_more").on("click",function(e){
    e.preventDefault();
    max_field = 10;
    x=1;
    var field_len = $('.menu_list').length;
    if(x<=max_field){
      x++;
      var html = $(".menu_list").first().clone();
      $(".menu_list").last().after(html);
      $('#item_name').val('');
      $('#price').val('');
      //alert(field_len+1);
      $("#item_name").last().attr("name","menu_item_name[item_name"+(field_len+1)+"]");
      $("#price").last().attr("name","menu_item_price[price"+(field_len+1)+"]");
    }
  })

   $("#new_restaurant").on("submit", function(event)
  {
    event.preventDefault();
    $('.menu_list').each(function(index)
    {
      var item_price = $('[name="menu_item_price[price'+(index+1)+']"]').val();
      var item_name =  $('[name="menu_item_name[item_name'+(index+1)+']"]').val();
      if(item_name=="" && item_price==""){
        alert("Put item name and item price before submitting!!!");
      }
      else if (item_name!="" && item_price=="")
      {
        alert("Please put item price!!")
      }
      else if(item_price!="" && item_name==""){
        alert("please put item name!!!");
      }
      else
      {
        $.ajax({ 
          type: "POST", 
          url: $("#new_restaurant").attr('action'), 
          data: $("#new_restaurant").serialize(),
          success: function(response) 
          { 

          } 
        });
        return false;
      }
    });
  });
</script>

app/views/restaurant/index.html.erb
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/tokenfield-typeahead.css">
<select name="filters" id="closed_on_filter">
  <option value="" selected="selected">Closed On</option>
  <option value="Sunday">Sunday</option>
  <option value="Monday">Monday</option>
  <option value="Tuesday">Tuesday</option>
  <option value="Wednesday">Wednesday</option>
  <option value="Thursday">Thursday</option>
  <option value="Friday">Friday</option>
  <option value="Saturday">Saturday</option>
</select><select name="filters" id="cuisine_filter">
  <option value="" selected="selected">Cuisine Type</option>
  <option value="Chinese">Chinese</option>
  <option value="Mughlai">Mughlai</option>
  <option value="Desert">Desert</option>
  <option value="South Indian">South Indian</option>
</select>
<select name="filters" id="blacklisted_filter">
  <option value="" selected="selected">Blacklisted Filter</option>
  <option value="true">Blacklisted</option>
  <option value="false">Not Blacklisted</option>
</select>
<select name="filters" id="deactive_filter">
  <option value="" selected="selected">Deactive Filter</option>
  <option value="true">Deactive</option>
  <option value="false">Not Deactive</option>
</select>


<div style="padding: 10px;">
  <table id="restaurants_datatable" class="table table-hover display responsive no-wrap" data-source="<%= restaurants_path(format: :json) %>">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Contact Number</th>
        <th scope="col">Operator</th>
        <th scope="col">Cuisine</th>
        <th scope="col">Timings</th>
        <th scope="col">Closed On</th>
        <th scope="col">Address</th>
        <th scope="col">Associated Blogs</th>
      </tr>
    </thead>
    <tbody>  
    </tbody>
  </table> 
</div>
<script>
  jQuery(document).ready(function() 
  {
    $('#restaurants_datatable').dataTable({
      "serverSide": true,
      "pagingType": "full_numbers",
      "oLanguage": { "sSearch": ""},
      "columnDefs": [
        { "orderable": false, "targets": 1 },
        { "orderable": false, "targets": 3 },
        { "orderable": false, "targets": 4 },
        { "orderable": false, "targets": 5 },
        { "orderable": false, "targets": 6 },
        { "orderable": false, "targets": 7 }

      ],
      "ajax":{
        "url":$('#restaurants_datatable').data('source'),
        "data": function (d) {
          d.cuisine = $("#cuisine_filter option:selected").val();
          d.closed_on = $("#closed_on_filter option:selected").val();
          d.is_blacklisted = $("#blacklisted_filter option:selected").val();
          d.is_deactive = $("#deactive_filter option:selected").val();
        }
      },
      "preDrawCallback": function(settings) 
      {
        $('#restaurants_datatable_filter input[type="search"]').attr("placeholder","Search");
        $(".loader").show();
      },
      "initComplete": function(settings, json) {
        $("#cuisine_filter").insertBefore('#restaurants_datatable_filter input[type="search"]');
        $("#closed_on_filter").insertBefore('#restaurants_datatable_filter');
        $("#blacklisted_filter").insertBefore('#restaurants_datatable_filter');
        $("#deactive_filter").insertBefore('#restaurants_datatable_filter');

      },
      "drawCallback": function(settings) 
      {
        $(".loader").hide();
      },
    });
    $("#cuisine_filter").on("change",function(){
      $('#restaurants_datatable').DataTable().ajax.reload(null,false);
    });
    $("#closed_on_filter").on("change",function(){
      $('#restaurants_datatable').DataTable().ajax.reload(null,false);
    });
    $("#blacklisted_filter").on("change",function(){
      $('#restaurants_datatable').DataTable().ajax.reload(null,false);
    });
    $("#deactive_filter").on("change",function(){
      $('#restaurants_datatable').DataTable().ajax.reload(null,false);
    });
  });

  function show(id)
  {
    window.location = "/restaurant/"+id;
  }
</script>
<style type="text/css">
  #restaurants_datatable_filter input[type="search"] {
    border: 1px solid #aaa;
    border-radius: 15px;
    padding: 5px;
    outline: none;
    margin-right: 16px;
}
#cuisine_filter{
  margin-right: 192px;
  float: left;
}
#closed_on_filter{
  margin-left: 17px;
  float: left;
}
#blacklisted_filter{
  margin-left: 25px;
}
#restaurants_datatable_length{
  margin-left: 10px;
}
#deactive_filter{
      margin-left: 25px;
}
</style>

app/views/restaurant/show.html.erb
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="http://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js"></script>
<div style="margin-left:227px" >
  <div class="card bg-light mb-3" style="max-width: 40rem;">
    <div class="card-header"><h3><center><strong><%= @restaurant.name.capitalize %></strong></center></h3></div>
      <div class="card-body">
        <%= form_for (@restaurant),:url =>"/restaurant/update/#{@restaurant.id}" ,:html => { :multipart => true } do |f| %>
          <h3>Restaurant #<%= @restaurant.id %></h3>
          <div class="field">
            <%= f.text_field :name,:class=>"form-control",:placeholder => "Name" %>
          </div>
          <br>
          <div class="field">
            <%= f.text_area :description,:placeholder => "Description",:class=>"form-control" %>
          </div>
          <br>

          <div class="row">
            <div class="col-sm-4">
              <div class="field">
                Blacklist : <%= f.check_box :is_blacklisted %>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="field">
                Deactivate: &nbsp;<%= f.check_box :is_deactive %>
              </div>
            </div>
          </div>
          <br>
          <div class="row">  
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :cuisine,:class=>"form-control",:id=>"cuisine" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :associated_blogs,:class=>"form-control",:id=>"associated_blogs",:placeholder=>"Associated Blogs" %>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :operator,:class=>"form-control" ,:placeholder => "Operator"%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :contact_number,:class=>"form-control" ,:placeholder => "Contact Number"%>
              </div>
            </div>
          </div>
          <br>
          <% if @restaurant.addresses.present? %>
            <%= f.fields_for @restaurant.addresses.first do |a|  %>
              <div class="field">
                  <%= a.text_area :address_line,:class=>"form-control" ,:style=>"min-height:120px;"%>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="field">
                    <%= a.text_field :latitude,:class=>"form-control",:placeholder => "Latitude",:id=>"latitude"  %>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="field">
                    <%= a.text_field :longitude,:class=>"form-control",:placeholder => "Longitude",:id=>"longitude"  %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
          <br>
          <div class="row">
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :opening_time,:id =>"timepickeropen",:class=>"form-control" ,:placeholder => "Opening Time"%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="field">
                <%= f.text_field :closing_time,:id =>"timepickerclose",:class=>"form-control" ,:placeholder => "Closing Time"%>
              </div>
            </div>
          </div>
          <br>

          <div class="field">
            <%= button_tag "View menu",:id => "view_menu",:class=>"btn btn-success",:data=>{:toggle=>"modal",:target=> "#myModal2"} %>
          </div>
          <% if @restaurant.associated_blogs.present? %>
            <br>
            <div class="field">
              <% blogs = @restaurant.associated_blogs.split(',') %>
              <% blogs.each do |i| %>
                <% b = Blog.where("id =?",i.to_i).first %>
                  <% if b.pictures.present? %>
                    <% b.pictures.each do |p| %>
                    <img src = "<%= p.avatar %>" style="height: 100px;width: 100px;cursor: pointer;" class = "pic_show"  data-id = "<%= p.id %>" data-toggle="modal" data-target= "#myModal" data-remote = "true">
                    <% end %>
                  <% end %>
                <% end %>
              <br>
            </div>
          <% end %>
          <br>
          <% if @restaurant.addresses.present? %>
            <div id="geolocation" style="width: 300px; height: 300px;"></div>
          <br>
          <% end %>
          <button type="submit" class="btn btn-primary btn_large" >Update</button>&nbsp;&nbsp;
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>



<!-- modal for picture show/like -->
<div id="myModal" class="modal" role="document" >
  <div class="modal-dialog">
    <div class="modal-content" style="width: 500px;height: 500px;">
      <div class="modal-body">
        <img src="" id = "modal-pic" style="width: 466px;height: auto;">
        <hr>
          <img src="/assets/pic_like.png" style="width: 20px;height: auto;cursor: pointer;" class="pic_like">
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>





<!-- Modal for menu_list -->
<div id="myModal2" class="modal" role="document"> 
  <div class="modal-dialog" style="max-width: 600px;" >
    <div class="modal-content" >
      <div class="modal-body2"  style="overflow-y: auto;max-height: 500px;">
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
  $('#cuisine').tokenfield({
    autocomplete: {
      source: ['Chinese','Moghlai','Desert','Indian','South Indian'],
      delay: 100
    },
    showAutocompleteOnFocus: true
  })

  var geocoder = new google.maps.Geocoder();
  if($("#restaurant_address_address_line").val()!=undefined)
  {
    var add =$("#restaurant_address_address_line").val().replace(/"/g,"");
  }

  geocoder.geocode( { 'address': add}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) 
    {
      var latitude = results[0].geometry.location.lat();
      var longitude = results[0].geometry.location.lng();  
      var map;
      function initialize() 
      {
        var myLatlng = new google.maps.LatLng(latitude, longitude);
        var myOptions = {
            zoom: 15,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById("geolocation"), myOptions);
        var marker = new google.maps.Marker({
            draggable: true,
            position: myLatlng,
            map: map
        });
        google.maps.event.addListener(marker, 'dragend', function (event) {

          document.getElementById("latitude").value = event.latLng.lat();
          document.getElementById("longitude").value = event.latLng.lng();
          
        });
      }
      google.maps.event.addDomListener(window, "load", initialize());
    }
  }); 
  


  $("#view_menu").on("click",function(e){  //  show modal for menu_list
    e.preventDefault();
    var id = <%= @restaurant.id %>
    $.ajax({ 
      async: true,
      type: 'GET',
      url: "/menu/"+id,
      success: function(data)
      {
        $(".modal-body2").html(data);  
      }, 
      error: function(data){ alert('error'); } 
    })
  });




  $(".pic_show").on("click",function(){  // show picture in modal

    var id = $(this).data('id');

    $.ajax({ 
      async: true,
      type: 'GET',
      url: "/restaurant/pic/show/"+id,
      success: function(data)
      {
        //alert(data.id);
        $("#modal-pic").attr("src",data.pic);
        $("#modal-pic").attr("data-id",data.id);  
        //$("#pic_like").attr("data-id",data.id);
        $(".pic_like").attr("id",data.id);

        var is_liked = data.is_liked;
        if(is_liked==true)
          $("#"+data.id).attr("src","/assets/pic_unlike.png");
        else
          $("#"+data.id).attr("src","/assets/pic_like.png");

      }, 
      error: function(data){ alert('error'); } 
    })
  });

  $('#timepickeropen').timepicker();
  $('#timepickerclose').timepicker();
  $(".pic_like").on("click",function()
  {
    var pic_id = $(".pic_like").attr("id");
      $.ajax({ 
      async: true,
      type: 'GET',
      url: "/like/pic_like/"+pic_id,
      success: function(data)
      {
        if(data.is_liked == true)
        {
          $("#"+data.pic_id).attr("src","/assets/pic_unlike.png");
        }
         else
        {
          $("#"+data.pic_id).attr("src","/assets/pic_like.png");
        }
      }, 
      error: function(data){ alert('error'); } 
    })
  });

  $(function(){
    $('#toggle-event-black_list').change(function() {
    })
  });

</script>
<style type="text/css">
.modal-backdrop 
  {
    position: absolute;
    right: 0;
    left: 0;
    opacity: 0.5;
    height:100%; 
    position: fixed;
  }

  .like_style
  {
    width: 20px;
    height: auto;
    cursor: pointer;
  }
.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}

</style>