config/routes.rb
StreetFeast::Application.routes.draw do
  get "blog/create"
  get "management/show_users"
  get "home/index"
  get "home/dashboard"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  get 'test_email' => 'application#test_email'

  get 'home/blacklist' => 'home#blacklist'

  post 'home/blacklist' => 'home#blacklist'

  get 'home/analytics' => 'home#analytics'

  post 'home/analytics' => 'home#analytics'

  get 'home/undo_blacklist' => 'home#undo_blacklist'

  post 'home/undo_blacklist' => 'home#undo_blacklist'
  
  get '/users' => 'user#index'

  get 'home/dashboard' => 'home#dashboard', as: :dashboard

  get 'home/dashboard_user' => 'home#dashboard_user'

  get 'user/:id/edit' => 'user#edit'

  get 'home/new_sms' => 'home#new_sms'

  post 'home/send_sms' => 'home#send_sms'

  patch 'user/:id/update' => 'user#update'

  post 'blog/create' => 'blog#create'

  post 'blog/create_blog_user' => 'blog#create_blog_user'

  get 'blog/new' => 'blog#new'

  get '/blogs' => 'blog#index'

  get 'blog/:id/edit' => 'blog#edit'

  get 'blog/:id' => 'blog#show'

  patch 'blog/update/:id' => 'blog#update'

  post 'blog/add_picture_to_blog' => 'blog#add_picture_to_blog'

  get 'user/show/:id' => 'user#show'

  patch 'user/update/:id' => 'user#update'

  delete 'user/photo_remove/:id' => "user#photo_remove"

  patch 'blog/update_blog_user/:id' => 'blog#update_blog_user'
  
  get 'restaurant/new/:id' => 'restaurant#new'

  post 'restaurant/create' => 'restaurant#create'

  get 'restaurant/:id' => 'restaurant#show'

  get 'restaurant/show_for_user/:id' => 'restaurant#show_for_user'

  get 'restaurant/pic/show/:id' => 'restaurant#show_pic'

  get 'like/pic_like/:id' => 'like#pic_like'

  get 'restaurant/address/:id' => 'restaurant#address'

  patch 'restaurant/update/:id' => 'restaurant#update'
  
  get 'menu/:id' => "menu#show"

  get "/restaurants" => "restaurant#index"
  get 'support_ticket/new' => "supportticket#new"

  post 'support_ticket/create' => 'supportticket#create'

  get '/support_tickets' => 'supportticket#index'

  get '/support_ticket/show/:id' => 'supportticket#show'

  get 'support_ticket/resolve' => "supportticket#resolve"

  get 'subscription/new' => 'subscription#new'

  post 'menu/create/:id' => 'menu#create'

  get '/menu/is_available/:id' => 'menu#is_available'

  get '/subscriptions' => 'subscription#index'

  get '/subscriptions/send_newsletter' => 'subscription#send_newsletter'

  post '/menu/edit_price' => 'menu#edit_price'

  get '/feedback/create' => 'feedback#create'

  get "payment/new" => "payment#new"

  post '/payment/create' => 'payment#create'

end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base
	belongs_to :user
	has_one :issue_type
end

app/controllers/supportticket_controller.rb
class SupportticketController < ApplicationController
  def new
    @support_ticket = SupportTicket.new
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: SupportTicketDatatable.new(view_context) }
    end
  end

  def show
    @support_ticket = SupportTicket.where("id=?",params[:id]).first
    render partial: 'supportticket/show'
  end


  def create
    if params[:support_ticket][:issue_type].present?
      issue_type_id = params[:support_ticket][:issue_type].to_i
      @support_ticket = SupportTicket.create(ticket_params)
      @support_ticket.update_attribute(:issue_type_id,issue_type_id)
      @support_ticket.save
      user_id = current_user.id
      @user = User.where("id=?",user_id)
      @support_ticket.update_attribute(:user_id,user_id)
      @support_ticket.save
      UserMailer.ticket_email_user(@user,@support_ticket).deliver
      UserMailer.ticket_email_admin(@user,@support_ticket).deliver
      flash[:notice] = "Ticket has been raised successfully.Please check you email for the Ticket ID"
    else
      flash[:notice] = "Please select Issue type"
    end
    redirect_to :back
  end

  def resolve
    issue_ids = params[:issue_ids]
    if issue_ids.present?
      issue_ids.each do |issue_id|
        @support_ticket = SupportTicket.where("id=?",issue_id).first
        @support_ticket.update_attribute(:is_resolved,true)
        @support_ticket.save
      end 
    render text: "success"
    else
      render text: "error"
    end
  end
 

  private
  def ticket_params
    params.require(:support_ticket).permit(:issue_description)
  end

end

app/views/supportticket/_show.html.erb
<div style="padding: 10px;" >
  <div class="field">
    <h5><strong>Issue ID:</strong></h5><%= @support_ticket.id %>
  </div>
  <br>
  <div class="field">
  <h5><strong>Issue Type:</strong></h5>
    <%= IssueType.find_by_id(@support_ticket.issue_type_id).issue_type %>   
  </div>
  <% if @support_ticket.issue_description.present? %>
    <br>
    <div class="field">
      <h5><strong>Issue Description:</strong></h5>
      <%= @support_ticket.issue_description %>
    </div>
  <% end %>
  <br>
  <br>
  <div class="field">
    <h5><strong>User email:</strong></h5>
    <%= @support_ticket.user.email %>
  </div>
  <br>
  <div class="field">
  <h5><strong>Contact number:</strong></h5>
    <%= @support_ticket.user.mobile_no %>   
  </div>
  <br>
  <div class="field">
  <h5><strong>Issue lodged on:</strong></h5>
    <%= @support_ticket.created_at %>   
  </div>

</div>

app/views/supportticket/index.html.erb
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<select name="filters" id="input_filter">
  <option value="" selected="selected">Select filter</option>
  <option value="resolved">Resolved</option>
  <option value="not resolved">Not Resolved</option>
</select>
<div style="padding: 10px;">
  <table id="tickets_datatable" class="table table-hover display responsive no-wrap" data-source="<%= support_tickets_path(format: :json) %>">
    <thead>
      <tr>
        <th scope="col"><input type="checkbox" name="select_all_checkbox" id="select_all"></th>
        <th scope="col">Issue ID</th>
        <th scope="col">Issue Type</th>
        <th scope="col">Issue Description</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  <a class="btn btn-success right-align resolve_issue_btn" >Resolve issue</a>
</div>

<input type="text" value="" name="HIIIII"  class="input_filter" style="display: none;">
<div id="myModal" class="modal" role="document">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> 
<script>

  jQuery(document).ready(function() 
  {

    var table = $('#tickets_datatable').dataTable({
      "serverSide": true,
      "pagingType": "full_numbers",
      "oLanguage": { "sSearch": ""},
      "columnDefs": [
        { "orderable": false, "targets": 0 },
        { "orderable": false, "targets": 2 },
        { "orderable": false, "targets": 4 },
        { "orderable": false, "targets": 5 }
      ],
      "ajax":{
        "url":$('#tickets_datatable').data('source'),
        "data": function (d) {
          d.is_resolved = $("#input_filter option:selected").val();
        }
      },
      "preDrawCallback": function(settings) 
      {
        $('#tickets_datatable_filter input[type="search"]').attr("placeholder","Search");
        $(".loader").show();
      },
      "initComplete": function(settings, json) {
        $("#input_filter").insertBefore('#tickets_datatable_filter input[type="search"]');

      },
      "drawCallback": function(settings) 
      {
        $(".loader").hide();
        initialize_script();
        count_rows =0;
        var x = $('#select_all').prop('checked');
        if(x==true)
        {
          $('#select_all').prop('checked',false);
        }
      },
    });
    $("#input_filter").on("change",function(){
      $('#tickets_datatable').DataTable().ajax.reload(null,false);
    });
  });

  var issue_id = [];
  var count_rows=0;
  var c_rows;
  function initialize_script()
  {
    
    $('#select_all').on("click",function() {
      var rows,checked,each_issue_id;
      issue_id=[];
      rows = $('#tickets_datatable').find('tbody tr').find('input');
      c_rows = rows.length;
      count_rows=rows.length;
      checked = $(this).prop('checked');
      
      $( ".is_checked_resolved" ).each(function() {
        $(this).prop('checked',checked);
        each_issue_id =$(this).attr("data-id") ;
        if(checked==true)
        {
          issue_id.push(parseInt(each_issue_id));
        }
        else
        {
          issue_id.pop();
          count_rows--;
          if(c_rows!=count_rows){
            $('#select_all').attr('checked',false);
          }
        }
      });

    });

    $(".is_checked_resolved").on("click",function()
    {
      rows = $('#tickets_datatable').find('tbody tr').find('input');
      c_rows = rows.length;
      var id = $(this).data('id');
      var x = $("#st_"+id).prop('checked');
      if(x == false)
      {
        var index = issue_id.indexOf(id);
        if (index !== -1) 
          issue_id.splice(index, 1);
        count_rows--;

        if(c_rows!=count_rows){
          var ch = $('#select_all');
          ch.prop('checked', false);
        }
      }
      else
      {
        issue_id.push(id);
        count_rows++;
        if(c_rows == count_rows){
          var ch = $('#select_all');
          ch.prop('checked', true);
        }
      }
    });

    $(".resolve_issue_btn").on("click",function(e){

      e.preventDefault();
      $.ajax({ 
        async: true,
        type: 'GET',
        url: "/support_ticket/resolve",
        data: {issue_ids: issue_id},
        success: function(data)
        {
          if(data=="success")
          {
            for (i = 0; i < issue_id.length; i++) 
            { 
              swal("Issues resolved!","", "success");
              $("#select_all").prop("checked",false);
              $(".is_resolved_"+issue_id[i]).attr("src","/assets/resolved_ticket.png")
              $("#st_"+issue_id[i]).remove();
              $(".is_resolved_"+issue_id[i]).css("display","");
            }
            issue_id=[];
          }  
          else
          {
            swal("Please select issue to be resolved","", "error");
          }
        }, 
        error: function(data){ alert('error'); } 
      })
    });

    $(".show_ticket").click(function(e)
    { 
      var id = $(this).attr('id'); 
      $.ajax({ 
        async: true,
        type: 'GET',
        url: "/support_ticket/show/"+id,
        success: function(data)
        {
          $(".modal-body").html(data);  
          $(".modal").show();
        }, 
        error: function(data){ alert('error'); } 
      })
    });
    $(".close").on("click",function(){
      $(".modal").hide();
    });
  }
</script>
<style type="text/css">
  .modal-backdrop
  {
    position: absolute;
    right: 0;
    left: 0;
    opacity:0.5 !important;
    height:100% 
  }

#tickets_datatable_filter input[type="search"] {
    border: 1px solid #aaa;
    border-radius: 15px;
    padding: 5px;
    outline: none;
    margin-right: 16px;
}
#input_filter{
  margin-right: 30px;
}
#tickets_datatable_length{
  margin-left: 10px;
}
table.dataTable th.select-checkbox:before { border-color: white; }
table.dataTable tr.selected th.select-checkbox:after { text-shadow: none; font-weight: normal;}

</style>

app/views/supportticket/new.html.erb
<center>
  <div class="card bg-light mb-3" style="max-width: 26rem;">
    <div class="card-header"><h2>Submit Issue</h2></div>
    <div class="card-body">
      <div class ="new_blog">
        <br>
        <%= form_for (@support_ticket),url: "/support_ticket/create", :html => { :multipart => true } do |f| %>
          <div class="form-group">
            <%= select_tag 'support_ticket[issue_type]',content_tag(:option,'Select Issue Type',:value=>"")+ options_from_collection_for_select(IssueType.all, 'id', 'issue_type'),:class=>"form-control" %>
          </div>
          <div class="field">
            <%= f.text_area :issue_description,:class=>"form-control",:placeholder => "Issue" %>
          </div>
          <br>
          <div class="actions">
            <button type="submit" class="btn btn-primary btn_large" >Submit</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</center>
<style type="text/css">
    .card {
    box-shadow: 0 10px 20px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}
</style>