config/routes.rb
StreetFeast::Application.routes.draw do
  get "blog/create"
  get "management/show_users"
  get "home/index"
  get "home/dashboard"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  get 'test_email' => 'application#test_email'

  get 'home/blacklist' => 'home#blacklist'

  post 'home/blacklist' => 'home#blacklist'

  get 'home/analytics' => 'home#analytics'

  post 'home/analytics' => 'home#analytics'

  get 'home/undo_blacklist' => 'home#undo_blacklist'

  post 'home/undo_blacklist' => 'home#undo_blacklist'
  
  get '/users' => 'user#index'

  get 'home/dashboard' => 'home#dashboard', as: :dashboard

  get 'home/dashboard_user' => 'home#dashboard_user'

  get 'user/:id/edit' => 'user#edit'

  get 'home/new_sms' => 'home#new_sms'

  post 'home/send_sms' => 'home#send_sms'

  patch 'user/:id/update' => 'user#update'

  post 'blog/create' => 'blog#create'

  post 'blog/create_blog_user' => 'blog#create_blog_user'

  get 'blog/new' => 'blog#new'

  get '/blogs' => 'blog#index'

  get 'blog/:id/edit' => 'blog#edit'

  get 'blog/:id' => 'blog#show'

  patch 'blog/update/:id' => 'blog#update'

  post 'blog/add_picture_to_blog' => 'blog#add_picture_to_blog'

  get 'user/show/:id' => 'user#show'

  patch 'user/update/:id' => 'user#update'

  delete 'user/photo_remove/:id' => "user#photo_remove"

  patch 'blog/update_blog_user/:id' => 'blog#update_blog_user'
  
  get 'restaurant/new/:id' => 'restaurant#new'

  post 'restaurant/create' => 'restaurant#create'

  get 'restaurant/:id' => 'restaurant#show'

  get 'restaurant/show_for_user/:id' => 'restaurant#show_for_user'

  get 'restaurant/pic/show/:id' => 'restaurant#show_pic'

  get 'like/pic_like/:id' => 'like#pic_like'

  get 'restaurant/address/:id' => 'restaurant#address'

  patch 'restaurant/update/:id' => 'restaurant#update'
  
  get 'menu/:id' => "menu#show"

  get "/restaurants" => "restaurant#index"
  get 'support_ticket/new' => "supportticket#new"

  post 'support_ticket/create' => 'supportticket#create'

  get '/support_tickets' => 'supportticket#index'

  get '/support_ticket/show/:id' => 'supportticket#show'

  get 'support_ticket/resolve' => "supportticket#resolve"

  get 'subscription/new' => 'subscription#new'

  post 'menu/create/:id' => 'menu#create'

  get '/menu/is_available/:id' => 'menu#is_available'

  get '/subscriptions' => 'subscription#index'

  get '/subscriptions/send_newsletter' => 'subscription#send_newsletter'

  post '/menu/edit_price' => 'menu#edit_price'

  get '/feedback/create' => 'feedback#create'

  get "payment/new" => "payment#new"

  post '/payment/create' => 'payment#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogs
  has_many :support_tickets
  require "rubygems"
  require "net/https"
  require "uri"
  require "json"
  devise :invitable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :invitable,:omniauthable, omniauth_providers: [:google_oauth2]

    def self.from_omniauth(access_token)
	    data = access_token.info
	    user = User.where(email: data['email']).first
	    user
	  end

    def self.send_sms(number,message)
      requested_url = 'https://api.textlocal.in/send/?'     
      uri = URI.parse(requested_url) #hash
      http = Net::HTTP.start(uri.host, uri.port) #new connection TCP & http  
      request = Net::HTTP::Get.new(uri.request_uri) 
      res = Net::HTTP.post_form(uri, 'apikey' => 'mve1n+0ecp4-VQPne3KkGkXWJ7cR2zzoowr1evMcU1', 'message' => message, 'sender' => 'TXTLCL', 'numbers' => number)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :verify_authenticity_token
  def show
    @user = User.find(params[:id]) 
    @picture = Picture.new
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(user_params)
    state = params[:state]
    @user.update_attribute(:state,state)
    @user.save
    if params[:user][:picture].present?
      if @user.picture.present?
        image = params[:user][:picture][:avatar]
        @user.picture.update_attribute(:avatar,image)
      else
        image = params[:user][:picture][:avatar]
        @picture = Picture.create(:avatar =>image,:user_id => @user.id)
      end
    end
    flash[:notice] = "User details updated"
    redirect_to :back
  end
  def photo_remove
    @user = User.find_by_id(params[:id])
    @image = @user.picture
    @image.destroy
    render text: "success"
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(view_context) }
    end
  end
  def update

    @user = User.find_by_id(params[:id])
    @user.update_attributes(user_params)
    if params[:user][:picture].present?
      @user_picture = Picture.create(:avatar=>params[:user][:picture][:avatar],:user_id=>params[:id])
    end
    state = params[:state]
    @user.update_attribute(:state,state)
    @user.save
    flash[:notice] = "User details updated"
    redirect_to :back
  end
  def edit
    @picture = Picture.new
    @user = User.find_by_id(params[:id])
  end




  private
    def user_params
      params.require(:user).permit(:fullname,:mobile_no,:city,:state,:email)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    email = request.env['omniauth.auth']['info']['email']
    @user = User.all.where("email =?",email).first
    if @user.present?
      if @user.sign_in_type.eql? "google"
        sign_in_and_redirect @user, event: :authentication
      else
        flash[:notice] = "You have already have an account!!!"
        redirect_to new_user_session_path
      end
    else
      @user = User.create(:email => email,:sign_in_type => "google")
      @user.save(validate: false)
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "You have successfully signed in"
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<style type="text/css">
    .card {
    box-shadow: 0 10px 20px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}
</style>
<center>
  <div class="card bg-light mb-3" style="max-width: 26rem;margin-top: 5%;">
    <div class="card-header"><b>Update Profile</b></div>
    <div class="card-body">
      <%= form_for (@user), url: "/user/#{@user.id}/update", :html => {:class =>"my_form",multipart: true} do |f| %>
        <fieldset>
          <% if @user.is_admin !=true %>
              <% if @user.fullname.present? %>
                <div class="form-group">
                  <%= f.text_field :fullname,:required => true,:class=>"form-control",placeholder: "Fullname" ,:disabled => "true", autofocus: true %>
                </div>
              <% else %>
                <div class="form-group">
                  <%= f.text_field :fullname,:required => true,:class=>"form-control",placeholder: "Fullname" , autofocus: true %>
                </div>
              <% end %>
              <div class="form-group">
                <%= f.text_field :email,:required => true,:class=>"form-control",placeholder: "Email" ,:disabled => "true" %>
              </div>
          <% else %>
            <div class="form-group">
              <%= f.text_field :fullname,:required => true,:class=>"form-control",placeholder: "Fullname" , autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.text_field :email,:required => true,:class=>"form-control",placeholder: "Email" %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.text_field :mobile_no,:required => true,:class=>"form-control",placeholder: "Mobile No"  %>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
               <%= f.text_field :city, class: 'form-control', id: 'city', placeholder: "Select city"%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <select class="form-control" id="state" name="state" value = "<%= @user.state%>">
                  <% if @user.state.present? %>
                  <option class=" form-text text-muted" value = "<%= @user.state%>"><%= @user.state%></option>
                  <% else %>
                  <option class=" form-text text-muted" value = "">Select your state</option>
                  <% end %>
                  <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                  <option value="Andhra Pradesh">Andhra Pradesh</option>
                  <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                  <option value="Assam">Assam</option>
                  <option value="Bihar">Bihar</option>
                  <option value="Chandigarh">Chandigarh</option>
                  <option value="Chhattisgarh">Chhattisgarh</option>
                  <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                  <option value="Daman and Diu">Daman and Diu</option>
                  <option value="Delhi">Delhi</option>
                  <option value="Goa">Goa</option>
                  <option value="Gujarat">Gujarat</option>
                  <option value="Haryana">Haryana</option>
                  <option value="Himachal Pradesh">Himachal Pradesh</option>
                  <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                  <option value="Jharkhand">Jharkhand</option>
                  <option value="Karnataka">Karnataka</option>
                  <option value="Kerala">Kerala</option>
                  <option value="Lakshadweep">Lakshadweep</option>
                  <option value="Madhya Pradesh">Madhya Pradesh</option>
                  <option value="Maharashtra">Maharashtra</option>
                  <option value="Manipur">Manipur</option>
                  <option value="Meghalaya">Meghalaya</option>
                  <option value="Mizoram">Mizoram</option>
                  <option value="Nagaland">Nagaland</option>
                  <option value="Orissa">Orissa</option>
                  <option value="Pondicherry">Pondicherry</option>
                  <option value="Punjab">Punjab</option>
                  <option value="Rajasthan">Rajasthan</option>
                  <option value="Sikkim">Sikkim</option>
                  <option value="Tamil Nadu">Tamil Nadu</option>
                  <option value="Tripura">Tripura</option>
                  <option value="Uttaranchal">Uttaranchal</option>
                  <option value="Uttar Pradesh">Uttar Pradesh</option>
                  <option value="West Bengal">West Bengal</option>
                </select>
              </div>
            </div>
          </div>
          <br>
          <div class="actions">
            <button type="submit" class="btn btn-primary btn_large">Update</button>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</center>
<style type="text/css">
  .btn_large
{
  width: 200px;
}
</style>
<script>
  $( function() {
    var availableTags = ["Mumbai","Delhi","Bangalore","Hyderabad","Ahmedabad","Chennai","Kolkata","Surat","Pune","Jaipur","Lucknow","Kanpur","Nagpur","Visakhapatnam","Indore"];
   
    $( "#city" ).autocomplete({
      source: availableTags
    });
  } );

</script>

app/views/user/index.html.erb
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<select name="filters" id="blocked_user_filter">
  <option value="" selected="selected">Blocked_user Filter</option>
  <option value="true">Blocked</option>
  <option value="false">Not Blocked</option>
</select>

<div style="padding: 10px;">
  <table id="users_datatable" class="table table-hover display responsive no-wrap" data-source="<%= users_path(format: :json) %>">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">email</th>
        <th scope="col">Mobile</th>
        <th scope="col">City</th>
        <th scope="col">State</th>
        <th scope="col">Posts</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        
    </tbody>
  </table>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('#users_datatable').dataTable({
      "serverSide": true,
      "pagingType": "full_numbers",
      "oLanguage": { "sSearch": ""},
      "columnDefs": [
        { "orderable": false, "targets": 6 },
        { "orderable": false, "targets": 7 },
        { "orderable": false, "targets": 0 },
        { "orderable": false, "targets": 5 }
      ],
      "ajax":{
        "url":$('#users_datatable').data('source'),
        "data": function (d) {
          d.is_blocked = $("#blocked_user_filter option:selected").val();
        }
      },
      "preDrawCallback": function(settings) 
      {
        $('#users_datatable_filter input[type="search"]').attr("placeholder","Search");
        $(".loader").show();
      },
      "initComplete": function(settings, json) {
        $("#blocked_user_filter").insertBefore('#users_datatable_filter input[type="search"]');
        
        $('.is_block_test').each(function() {
          if($(this).hasClass("unblock")){
            $(this).closest("tr").addClass("table-warning");
          }else{
            $(this).addClass("block");
          }
        })

      },
      "drawCallback": function(settings) 
      {
        $(".loader").hide();
        initialize_script();
      }
    });
    $("#users_datatable_filter").on("change",function(){
      $('#users_datatable').DataTable().ajax.reload(null,false);
    });
  });


function initialize_script(){

  $(".is_block_test").click(function(){
    var user_id = $(this).data('id');
    var is_blocked = $(this).hasClass("unblock");
    if(is_blocked==false)
    {
      swal({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, block!'
      }).then((result) =>
      {
        $(this).closest('tr').addClass("table-warning");
        $(this).addClass("unblock").removeClass("block");
        $.getScript('/home/blacklist.js?pt=' + user_id);
      })
    }
    else
    {
      swal({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, block!'
      }).then((result) => 
      {
        $(this).closest('tr').removeClass("table-warning");
        $(this).addClass("block").removeClass("unblock");
        $.getScript('/home/undo_blacklist.js?pt=' + user_id);
      }) 
    }
  });
}
</script>
<style>
  .unblock
  {
    filter: grayscale(100%);
    opacity: 0.7;
  }

  #example_wrapper .row:first-child{
    margin-bottom: 24px;
  }
  #users_datatable_filter input[type="search"] {
    border: 1px solid #aaa;
    border-radius: 15px;
    padding: 5px;
    outline: none;
    margin-right: 16px;
}
#blocked_user_filter{
  margin-right: 576px;
  float: left;
}
span.user_name {
  margin-left: 5px;
}
a:hover{
  text-decoration: none;
}
</style>

app/views/user/show.html.erb
<style type="text/css">
    .card {
    box-shadow: 0 10px 20px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}
</style>
<center>
  <div class="card bg-light mb-3" style="max-width: 26rem; margin-top: 5%;">
    <div class="card-header"><b>Profile</b></div>
    <div class="card-body">
      <%= form_for (@user), url: "/user/update/#{@user.id}", :html => {:class =>"my_form",multipart: true} do |f| %>
        <fieldset>
          <br>
          <div class="form-group">
            <%= f.text_field :fullname,:required => true,:class=>"form-control",placeholder: "Fullname" , autofocus: true %>
          </div>
	        <div class="form-group">
	          <%= f.text_field :email,:required => true,:class=>"form-control",placeholder: "Email"  %>
	        </div>
          <div class="form-group">
            <%= f.text_field :mobile_no,:required => true,:class=>"form-control",placeholder: "Mobile No"  %>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
               <%= f.text_field :city, class: 'form-control', id: 'city', placeholder: "Select city"%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <select class="form-control" id="state" name="state" value = "<%= @user.state%>">
                  <% if @user.state.present? %>
                  <option class=" form-text text-muted" value = "<%= @user.state%>"><%= @user.state%></option>
                  <% else %>
                  <option class=" form-text text-muted" value = "">Select your state</option>
                  <% end %>
                  <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                  <option value="Andhra Pradesh">Andhra Pradesh</option>
                  <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                  <option value="Assam">Assam</option>
                  <option value="Bihar">Bihar</option>
                  <option value="Chandigarh">Chandigarh</option>
                  <option value="Chhattisgarh">Chhattisgarh</option>
                  <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                  <option value="Daman and Diu">Daman and Diu</option>
                  <option value="Delhi">Delhi</option>
                  <option value="Goa">Goa</option>
                  <option value="Gujarat">Gujarat</option>
                  <option value="Haryana">Haryana</option>
                  <option value="Himachal Pradesh">Himachal Pradesh</option>
                  <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                  <option value="Jharkhand">Jharkhand</option>
                  <option value="Karnataka">Karnataka</option>
                  <option value="Kerala">Kerala</option>
                  <option value="Lakshadweep">Lakshadweep</option>
                  <option value="Madhya Pradesh">Madhya Pradesh</option>
                  <option value="Maharashtra">Maharashtra</option>
                  <option value="Manipur">Manipur</option>
                  <option value="Meghalaya">Meghalaya</option>
                  <option value="Mizoram">Mizoram</option>
                  <option value="Nagaland">Nagaland</option>
                  <option value="Orissa">Orissa</option>
                  <option value="Pondicherry">Pondicherry</option>
                  <option value="Punjab">Punjab</option>
                  <option value="Rajasthan">Rajasthan</option>
                  <option value="Sikkim">Sikkim</option>
                  <option value="Tamil Nadu">Tamil Nadu</option>
                  <option value="Tripura">Tripura</option>
                  <option value="Uttaranchal">Uttaranchal</option>
                  <option value="Uttar Pradesh">Uttar Pradesh</option>
                  <option value="West Bengal">West Bengal</option>
                </select>
              </div>
            </div>
          </div>
          <br>
          <div class="actions">
            <button type="submit" class="btn btn-primary btn_large">Update</button>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</center>