config/routes.rb
StreetFeast::Application.routes.draw do
  get "blog/create"
  get "management/show_users"
  get "home/index"
  get "home/dashboard"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  get 'test_email' => 'application#test_email'

  get 'home/blacklist' => 'home#blacklist'

  post 'home/blacklist' => 'home#blacklist'

  get 'home/analytics' => 'home#analytics'

  post 'home/analytics' => 'home#analytics'

  get 'home/undo_blacklist' => 'home#undo_blacklist'

  post 'home/undo_blacklist' => 'home#undo_blacklist'
  
  get '/users' => 'user#index'

  get 'home/dashboard' => 'home#dashboard', as: :dashboard

  get 'home/dashboard_user' => 'home#dashboard_user'

  get 'user/:id/edit' => 'user#edit'

  get 'home/new_sms' => 'home#new_sms'

  post 'home/send_sms' => 'home#send_sms'

  patch 'user/:id/update' => 'user#update'

  post 'blog/create' => 'blog#create'

  post 'blog/create_blog_user' => 'blog#create_blog_user'

  get 'blog/new' => 'blog#new'

  get '/blogs' => 'blog#index'

  get 'blog/:id/edit' => 'blog#edit'

  get 'blog/:id' => 'blog#show'

  patch 'blog/update/:id' => 'blog#update'

  post 'blog/add_picture_to_blog' => 'blog#add_picture_to_blog'

  get 'user/show/:id' => 'user#show'

  patch 'user/update/:id' => 'user#update'

  delete 'user/photo_remove/:id' => "user#photo_remove"

  patch 'blog/update_blog_user/:id' => 'blog#update_blog_user'
  
  get 'restaurant/new/:id' => 'restaurant#new'

  post 'restaurant/create' => 'restaurant#create'

  get 'restaurant/:id' => 'restaurant#show'

  get 'restaurant/show_for_user/:id' => 'restaurant#show_for_user'

  get 'restaurant/pic/show/:id' => 'restaurant#show_pic'

  get 'like/pic_like/:id' => 'like#pic_like'

  get 'restaurant/address/:id' => 'restaurant#address'

  patch 'restaurant/update/:id' => 'restaurant#update'
  
  get 'menu/:id' => "menu#show"

  get "/restaurants" => "restaurant#index"
  get 'support_ticket/new' => "supportticket#new"

  post 'support_ticket/create' => 'supportticket#create'

  get '/support_tickets' => 'supportticket#index'

  get '/support_ticket/show/:id' => 'supportticket#show'

  get 'support_ticket/resolve' => "supportticket#resolve"

  get 'subscription/new' => 'subscription#new'

  post 'menu/create/:id' => 'menu#create'

  get '/menu/is_available/:id' => 'menu#is_available'

  get '/subscriptions' => 'subscription#index'

  get '/subscriptions/send_newsletter' => 'subscription#send_newsletter'

  post '/menu/edit_price' => 'menu#edit_price'

  get '/feedback/create' => 'feedback#create'

  get "payment/new" => "payment#new"

  post '/payment/create' => 'payment#create'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :pictures
	belongs_to :user
	belongs_to :restaurant
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    if blog_params[:title].present? && blog_params[:content].present?
      @blog  = Blog.create(blog_params)
      if blog_params[:fullname].nil?
        @blog.fullname = "Annonymus"
      end
      if blog_params[:email].nil?
        @blog.email = "Annonymus"
      end
      @blog.is_reviewed = false
      @blog.is_blocked = false
      @blog.save
      if params[:blog][:picture].nil?
        redirect_to :back
        flash[:notice]= "Blog has been created successfully!"
      else
        params[:blog][:picture][:avatar].each do |c|
          Picture.create(:avatar=> c,:blog_id => @blog.id)
        end
        flash[:notice]= "Blog has been created successfully!"
        redirect_to :back
      end
    else
      flash[:notice] = "Title and Content are mandatory!!"
      redirect_to :back
    end
  end

  def new
    @blog = Blog.new
    @picture = Picture.new
  end

  def create_blog_user
    if blog_params[:title].present? && blog_params[:content].present?
      @blog  = Blog.create(blog_params)
      @blog.user_id = current_user.id
      @blog.fullname = current_user.fullname
      @blog.email = current_user.email
      @blog.is_reviewed = false
      @blog.is_blocked = false
      @blog.save
      unless params[:blog][:picture].nil?
        params[:blog][:picture][:avatar].each do |c|
          Picture.create(:avatar=> c,:blog_id => @blog.id)
        end
      end
      if current_user.is_admin == true
        flash[:notice]= "Blog has been created successfully!"
        redirect_to dashboard_path
      else
        flash[:notice]= "Blog has been created successfully!"
        redirect_to home_dashboard_user_path
      end
    else
      redirect_to :back
      flash[:notice] = "Title and Content are mandatory!!"
    end
  end

  def update_blog_user
    if blog_params[:title].present? && blog_params[:content].present?
      @blog = Blog.find_by_id(params[:id])
      @blog.update_attributes(blog_params)
      @blog.user_id = current_user.id
      @blog.save
      unless params[:blog][:picture].nil?
        params[:blog][:picture][:avatar].each do |c|
          Picture.create(:avatar=> c,:blog_id => @blog.id)
        end
      end
      if current_user.is_admin == true
        flash[:notice]= "Blog details successfully updated!"
        redirect_to :back
      else
        flash[:notice]= "Blog details successfully updated!"
        redirect_to :back
      end
    else
      redirect_to :back
      flash[:notice] = "Title and Content are mandatory!!"
    end  
  end

  def edit
    @blog = Blog.find_by_id(params[:id])
    if @blog.present?
      if @blog.is_reviewed.eql? false
        @blog.is_reviewed = true
        @blog.save
      end
      @picture = Picture.new
    end
    render partial: "edit"
  end

  def update
    @blog = Blog.find_by_id(params[:id])
    @blog.update_attributes(blog_params)
    render json: @blog
  end

  def add_picture_to_blog
    picture = params[:pic].to_jsons
    render text: "uploaded"
  end


  def show
    @blog = Blog.find_by_id(params[:id])
    @picture = Picture.new
    if @blog.is_reviewed.eql? false
      @blog.is_reviewed = true
      @blog.save
    end
  end

  def index
     respond_to do |format|
      format.html
      format.json { render json: BlogDatatable.new(view_context) }
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content,:email,:fullname)
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_edit.html.erb
<style type="text/css">
  .uploadpic{
    display: none;
  }
</style>
<%= tinymce%>
<%= form_for (@blog),url: "/blog/update/#{@blog.id}", :html => { :multipart => true },:id =>"editblog",:remote => true,"data-id" => "#{@blog.id}" do |f| %>
  <div class="field">
    <%= f.text_field :title,:class=>"form-control",:placeholder => "Title" %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :content, :class => "tinymce" %>
  </div>
  <div class="field">
    <%= f.fields_for @picture do |a|  %>
      <%= a.file_field :avatar,:class => "uploadpic",:id => "upload_pic"%>
    <% end %>
  </div>
  <br/>
  <div>
    <% @blog.pictures.each do |p| %>
      <img src="<%= p.avatar %>" id = "<%=p.id %>" style="height: 100px;width: 100px;"> &nbsp;&nbsp;&nbsp;
    <% end %>
  </div>
  <br>
  <div class="actions">
    <button type="submit" class="btn btn-primary btn_large" >Update</button>
  </div>
<% end %>
<script type="text/javascript">
  tinymce.remove();
  tinymce.init({ selector: ".tinymce" })


  $(".edit_blog").on("submit", function(event){ 
    var id = <%= @blog.id %>
    $.ajax({ type: "POST",
     url: this.action,
      data: $(this).serialize(), 
      success: function(response) 
      {
          text_truncate = function(str, length, ending)
           {
            if (length == null) {
              length = 100;
            }
            if (ending == null) {
              ending = '...';
            }
            if (str.length > length) {
              return str.substring(0, length - ending.length) + ending;
            } else {
              return str;
            }
          };
        $('.modal-backdrop').remove();
        $('.modal').hide();
        $('.blog_title_'+id).html(response.title);
        $('.blog_content_'+id).html(text_truncate(response.content,30,"..."));
      } 
    }); 
    event.preventDefault(); 
  }); 


  // $(".add_image_blog").on("click",function(event){



  //   //var file_data = $(".uploadpic").prop("files")[0];
  //   $(".uploadpic").trigger("click");
  //   var x= $(".uploadpic").val();
  //   //$("#upload_pic").removeClass("uploadpic");
  //   console.log(x);



  //   //var x = $("#upload_pic").val();
  //   //alert(x)
  //   //$("#upload_pic").addClass("uploadpic");

  //   //var files = document.getElementById("upload_pic").files;
  //   //var length = files.length;


  //   //var files = $(".uploadpic").val();

  //   //var fl = files.length;

  //   //alert(files);


  //   //alert(image);
  //   //alert(JSON.stringify(file_data));
  //   //alert(JSON.stringify(x));
  //   // $.ajax({ 
  //   //   type: "POST",
  //   //   url: "/blog/add_picture_to_blog",
  //   //   data: {'blog_id' :<%= @blog.id %>,'pic' :JSON.stringify(x)}, 
  //   //   success: function(response) 
  //   //   {
  //   //     alert(response);       
  //   //   } 
  //   // }); 
  // });
</script>

app/views/blog/index.html.erb
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<select name="filters" id="reviewed_filter">
  <option value="" selected="selected">Review Filter</option>
  <option value="true">Reviewed</option>
  <option value="false">Not Reviewed</option>
</select>
<select name="filters" id="blocked_filter">
  <option value="" selected="selected">Block Filter</option>
  <option value="true">Blocked</option>
  <option value="false">Not Blocked</option>
</select>



<div style="padding: 10px;">
  <table id="blog_datatable" class="table table-hover display responsive no-wrap" data-source="<%= blogs_path(format: :json) %>">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
        <th scope="col">Email</th>
        <th scope="col">Pictures</th>
        <th scope="col">Created at</th>
        <th scope="col">Updated At </th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      
    </tbody>
  </table> 
</div>
<div id="myModal" class="modal" role="document">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Modal Header</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        
      </div>
    </div>
  </div>
</div>
<%= tinymce %>
<script>
  jQuery(document).ready(function() 
  {
    $('#blog_datatable').dataTable({
      "serverSide": true,
      "pagingType": "full_numbers",
      "oLanguage": { "sSearch": ""},
       "columnDefs": [
        { "orderable": false, "targets": 4 },
        { "orderable": false, "targets": 2 },
        { "orderable": false, "targets": 0 },
        { "orderable": false, "targets": 3 },
        { "orderable": false, "targets": 7 }
      ],
      "ajax":{
        "url":$('#blog_datatable').data('source'),
        "data": function (d) {
          d.is_reviewed = $("#reviewed_filter option:selected").val();
          d.is_blocked = $("#blocked_filter option:selected").val();
        }
      },
      "preDrawCallback": function(settings) 
      {
        $('#blog_datatable_filter input[type="search"]').attr("placeholder","Search");
        $(".loader").show();
      },
      "initComplete": function(settings, json) {
        $("#reviewed_filter").insertAfter('#blog_datatable_length');
        $("#blocked_filter").insertAfter('#reviewed_filter');
        
      },
      "drawCallback": function(settings) 
      {
        initialize_script();
        $(".loader").hide();
      },
    });
    $("#reviewed_filter").on("change",function(){
      $('#blog_datatable').DataTable().ajax.reload(null,false);
    });


    $("#blocked_filter").on("change",function(){
      $('#blog_datatable').DataTable().ajax.reload(null,false);
    });
  });

  function show(id)
  {
    window.location = "/blog/"+id;
  }
function initialize_script()
{
  $(".blog_edit").click(function(e)
  { 
    var id = $(this).attr('id');
    $.ajax({ 
      async: true,
      type: 'GET',
      url: "/blog/"+id+"/edit",
      success: function(data)
      {
        $(".modal-body").html(data);
        $(".modal").show();  
      }, 
      error: function(data){ alert('error'); } 
    })
  });
  
  $(".close").on("click",function(){
    $(".modal").hide();  
  })
}
</script>

<style>

.modal-backdrop {
  position: absolute;
  right: 0;
  left: 0;
  opacity: 0.5;
  height:100% 
  }
  #example_wrapper .row:first-child{
    margin-bottom: 24px;
  }
#blog_datatable_filter input[type="search"] {
    border: 1px solid #aaa;
    border-radius: 15px;
    padding: 5px;
    outline: none;
    margin-right: 16px;
}
#reviewed_filter{
  float: left;
  margin-left: 18px;
}
#blocked_filter{
  margin-left: 25px;
}
.reset_filters{
  margin-left: 25px;
}
.modal-body{
  height: 500px;
  overflow-y: auto;
}
.modal-dialog{
  overflow-y: initial !important
}
</style>

app/views/blog/new.html.erb
<div style="padding: 20px;">
  <div class="card" style="padding: 10px;">
    <div class="container-fluid">
      <div class ="new_blog">
        <h1>Create a new blog</h1>
        <%= form_for (@blog),url: "/blog/create_blog_user", :html => { :multipart => true } do |f| %>
          <div class="field">
            <%= f.text_field :title,:class=>"form-control",:placeholder => "Title" %>
          </div>
          <br>

          <div class="field">
            <%= f.text_area :content, :class => "tinymce",:placeholder => "Content" %>
          </div>
          <br>
          <div class="field">
            <%= f.fields_for @picture do |a|  %>
              <b> Upload Images : </b>
              <%= a.file_field :avatar , multiple: true %>
            <% end %>
          </div>
          <br/>
          <div class="actions">
            <button type="submit" class="btn btn-primary btn_large" >Create</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .card {
    box-shadow: 0 10px 20px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}
</style>

app/views/blog/show.html.erb
<!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
<div style="padding: 20px;">
  <div class="card" style="padding: 10px;">
    <div class="container-fluid">
      <div class ="new_blog">
        <%= form_for (@blog),url: "/blog/update_blog_user/#{@blog.id}", :html => { :multipart => true } do |f| %>
          <h3>Blog #<%= @blog.id %></h3>
          <div class="field">
            <%= f.text_field :title,:class=>"form-control",:placeholder => "Title" %>
          </div>
          <br>

          <div class="field">
            <%= f.text_area :content, :class => "tinymce",:placeholder => "Content" %>
          </div>
          <br>
          <div class="field">
            <% @blog.pictures.each do |p| %>
              <img src="<%= p.avatar %>" id = "<%=p.id %>" style="height: 100px;width: 100px;"> &nbsp;&nbsp;&nbsp;
            <% end %>
          </div>
          <br/>
          <div class="field">
            <%= f.fields_for @picture do |a|  %>
              <b> Upload Images : </b>
              <%= a.file_field :avatar , multiple: true %>
            <% end %>
          </div>
          <br>
          <div class="actions">
            <button type="submit" class="btn btn-primary btn_large" >Update</button>&nbsp;&nbsp;
            <button type="submit" class="btn btn-primary btn_large" id="add_to_restaurant" data-id="<%=@blog.id %>" data-toggle="modal" data-target="#myModal" >Add to restaurant</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div id="myModal" class="modal" role="document">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">ADD TO RESTAURANT</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        
      </div>
    </div>
  </div>
</div>

<script>
  $("#add_to_restaurant").on("click",function(e){
    e.preventDefault();
    var id = $(this).data('id');
    $.ajax({ 
      async: true,
      type: 'GET',
      url: "/restaurant/new/"+id,
      success: function(data)
      {
        $(".modal-body").html(data);  
      }, 
      error: function(data){ alert('error'); } 
    })
  })



</script>
<style>

.modal-backdrop {
  position: absolute;
  right: 0;
  left: 0;
  opacity: 0.5;
  height:100% ;
  position: fixed;
  }
  #example_wrapper .row:first-child{
    margin-bottom: 24px;
  }
  .card {
    box-shadow: 0 10px 20px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border: 1px solid;
    border-radius: 5px;
    height: auto;
}
</style>